version: "3.7"

services:
  alice:
    image: web_py
    environment:
      - alice
    expose:
      - 5000
    networks:
      - internal_network

  bob:
    image: web_py
    environment:
      - bob
    expose:
      - 5000
    networks:
      - internal_network

  nginx_prox:
    image: proxy
    depends_on:
      - alice
      - bob
    volumes:
    #  - /Users/nicolamanuelmorillomartinez/Desktop/Airelogic/reverse_prox/nginx.conf:/etc/nginx/nginx.conf
    # - "C:\\Users\\nicol\\Desktop\\airelogic\\Airelogic\\reverse_prox\\nginx.conf:/etc/nginx/nginx.conf"
      - ./reverse_prox/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - 8080:80
    networks:
      - internal_network
      - external_network

networks:
  external_network:
    name: external_network

  internal_network:
    external: false
    name: internal_network
