version: "3.7"

services:
  alice:
    image: flask2
    environment:
      - Alice
    expose:
      - 5000
    networks:
      - my_project_network

  bob:
    image: flask2
    environment:
      - Bob
    expose:
      - 5000
    networks:
      - my_project_network

  nginx_prox:
    image: prox
    depends_on:
      - alice
      - bob
    volumes:
      - /Users/nicolamanuelmorillomartinez/Desktop/Airelogic/reserve_prox/nginx.conf:/etc/nginx/nginx.conf
    # - "C:\\Users\\nicol\\Desktop\\airelogic\\Airelogic\\reserve_prox\\nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 8080:80
    networks:
      - my_project_network

networks:
  my_project_network:
    external: false
    name: my_project_network