version: "3.7"

services:
  alice:
    image: flask2
    environment:
      - Alice
    expose:
      - 5000
    networks:
      - internal_network_1

  bob:
    image: flask2
    environment:
      - Bob
    expose:
      - 5000
    networks:
      - internal_network_1

  nginx_prox:
    image: prox
    depends_on:
      - alice
      - bob
    volumes:
      - /Users/nicolamanuelmorillomartinez/Desktop/Airelogic/reserve_prox/nginx.conf:/etc/nginx/nginx.conf
    # - "C:\\Users\\nicol\\Desktop\\airelogic\\Airelogic\\reserve_prox\\nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 8080:80
    networks:
      - internal_network_1
      - external_network

networks:
  external_network:
    name: external_network

  internal_network_1:
    external: false
    name: internal_network_1
