FROM debian:latest

ENV NAME="Nico"
RUN apt-get update \
    && apt install -y wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev \
    && apt-get install python3 -y \
    && apt-get install python3-pip -y \
    && pip3 install flask 

#RUN apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev

RUN mkdir ~/server
WORKDIR /server

COPY server.py server.py



EXPOSE 5000

CMD ["python3", "server.py"]