FROM debian:latest

ENV NAME="Nico"
RUN apt-get update
RUN apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
RUN apt install python3 -y
RUN apt install python3-pip -y
RUN pip3 install flask

RUN mkdir ~/server
WORKDIR /server

COPY server.py server.py



EXPOSE 5000

CMD ["python3", "server.py"]