FROM debian:latest

ENV NAME="Nico"
RUN apt-get update \
    && apt install -y wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev \
    && apt-get install python3 -y \
    && apt-get install python3-pip -y \
    && pip3 install flask 

RUN mkdir ~/server
WORKDIR /server

COPY server.py server.py



EXPOSE 8080

CMD ["python3", "server.py"]