on:
  workflow_dispatch:
    inputs:
      action:
        description: up or down the docker process
        requiere: true
        type: choice
        options:
        - up
        - down

jobs:
  deploy:

    if: ${{ github.event.inputs.action == 'up' }}
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build image web_py
      working-directory: ./flask
      run: docker build -t web_py .

    - name: Build image prox
      working-directory: ./reverse_prox
      run: docker build -t prox .

    - name: Compose file
      run: docker-compose up -d

    - name: Check Bob
      run: curl -I localhost:8080/bob

    - name: Check Alice
      run: curl -I localhost:8080/alice

    - name: Check Nico
      run: curl -I localhost:8080/nico

    - name: Check host
      run: curl -I localhost:8080/


